spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/file?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 100000MB
server:
  port: 8888


#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath*:com/acmlab/file/mapper/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: mapper/*.xml
logging:
  level:
    com:
      acmlab:
        file:
          mapper: debug